NOTIFICATION_MESSAGES = {
    "LOW_LEAVE_BALANCE": "Your leave balance is below the threshold: {balance} days.",
    "EMPLOYEE_LATE": "You were late by {minutes} minutes today.",
    "CHECK_IN": "You successfully checked in at {time}.",
    "CHECK_OUT": "You successfully checked out at {time}.",
    "DAILY_WORK_SUMMARY": "Your total work hours today: {hours}.",
    "LEAVE_REQUEST": "Your leave request is now {status}.",
    "INSUFFICIENT_LEAVE": "Your leave balance is insufficient for the requested leave.",
    "LEAVE_BALANCE_UPDATED": "Your leave balance has been updated. Remaining leave: {balance} days.",
    "CLASHING_LEAVE": "Your leave request conflicts with another request on these days: {days}.",
    "LATENESS": "You were late by {minutes} minutes today.",
    "NO_CHECK_IN": "You have not checked in today.",
    "LEAVE_CANCELLED": "You have successfully cancelled your leave request.",
    "ERROR": "An error occurred: {error}",
    "INVALID_LOGIN": "Invalid username or password.",
    "TOKEN_EXPIRED": "Your session has expired. Please log in again.",
    "TOKEN_INVALID": "Invalid token. Access denied.",
    "PERMISSION_DENIED": "You do not have permission to perform this action.",
    "ACCOUNT_LOCKED": "Your account is temporarily locked due to multiple failed login attempts.",
    "PASSWORD_RESET": "Your password has been successfully reset.",
    "PASSWORD_RESET_FAILED": "Failed to reset your password. Please try again later.",
    "UNAUTHORIZED_ACCESS": "Unauthorized access attempt detected.",
    "INTERNAL_SERVER_ERROR": "An unexpected error occurred. Please try again later.",
    "PROFILE_UPDATED": "Your profile has been successfully updated.",
    "INVALID_INPUT": "Invalid input detected: {input_field}.",
    "DATA_SAVED": "Your changes have been saved successfully.",
    "ACTION_COMPLETED": "The requested action has been completed successfully.",
    "ACTION_FAILED": "Failed to complete the requested action: {reason}.",
    "DUPLICATE_ENTRY": "This entry already exists: {entry}.",
    "LEAVE_APPROVED":"Your leave request (ID: {leave_id}) from {start_date} to {end_date} has been approved.",
    "LEAVE_REJECTED":  "Your leave request (ID: {leave_id}) from {start_date} to {end_date} has been rejected.",
    "LEAVE_CANCELLED": "Your leave request (ID: {leave_id}) has been cancelled.",
}
NOTIFICATION_DEFAULTS = {
    "LOW_LEAVE_BALANCE": {"severity": "warning", "type": "persistent"},
    "EMPLOYEE_LATE": {"severity": "warning", "type": "temporary"},
    "CHECK_IN": {"severity": "success", "type": "temporary"},
    "CHECK_OUT": {"severity": "success", "type": "temporary"},
    "DAILY_WORK_SUMMARY": {"severity": "info", "type": "temporary"},
    "LEAVE_REQUEST": {"severity": "info", "type": "persistent"},
    "INSUFFICIENT_LEAVE": {"severity": "danger", "type": "temporary"},
    "LEAVE_BALANCE_UPDATED": {"severity": "info", "type": "temporary"},
    "CLASHING_LEAVE": {"severity": "warning", "type": "temporary"},
    "LATENESS": {"severity": "warning", "type": "temporary"},
    "NO_CHECK_IN": {"severity": "warning", "type": "temporary"},
    "LEAVE_CANCELLED": {"severity": "success", "type": "temporary"},
    "ERROR": {"severity": "danger", "type": "temporary"},
    "INVALID_LOGIN": {"severity": "danger", "type": "temporary"},
    "TOKEN_EXPIRED": {"severity": "danger", "type": "temporary"},
    "TOKEN_INVALID": {"severity": "danger", "type": "temporary"},
    "PERMISSION_DENIED": {"severity": "danger", "type": "temporary"},
    "ACCOUNT_LOCKED": {"severity": "warning", "type": "persistent"},
    "PASSWORD_RESET": {"severity": "success", "type": "temporary"},
    "PASSWORD_RESET_FAILED": {"severity": "danger", "type": "temporary"},
    "UNAUTHORIZED_ACCESS": {"severity": "danger", "type": "temporary"},
    "INTERNAL_SERVER_ERROR": {"severity": "danger", "type": "temporary"},
    "PROFILE_UPDATED": {"severity": "success", "type": "temporary"},
    "INVALID_INPUT": {"severity": "warning", "type": "temporary"},
    "DATA_SAVED": {"severity": "success", "type": "temporary"},
    "ACTION_COMPLETED": {"severity": "success", "type": "temporary"},
    "ACTION_FAILED": {"severity": "danger", "type": "temporary"},
    "DUPLICATE_ENTRY": {"severity": "warning", "type": "temporary"},
    "LEAVE_APPROVED": {"severity": "success", "type": "temporary"},
    "LEAVE_REJECTED": {"severity": "danger", "type": "temporary"},
    "LEAVE_CANCELLED": {"severity": "warning", "type": "temporary"},
}